---
.gitlab-ci.yml:
  delete: true
.rubocop.yml:
  default_configs:
    AllCops:
      TargetRubyVersion: '2.3'
    'Style/FrozenStringLiteralComment':
      Enabled: false
.travis.yml:
  remove_includes:
    -
      env: PUPPET_GEM_VERSION="~> 5.0" CHECK=parallel_spec
      rvm: 2.4.4
    -
      env: PUPPET_GEM_VERSION="~> 4.0" CHECK=parallel_spec
      rvm: 2.1.9
appveyor.yml:
  delete: true
spec/spec_helper.rb:
  mock_with: ':rspec'
